services:
  rediscan:
    build:
      context: .
      dockerfile: Dockerfile
    read_only: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PORT}:8080"
    environment:
      - REDIS_ADDR=${REDIS_ADDR:-host.docker.internal:6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - PORT=8080
    restart: on-failure:10
